### PR TITLE
changing editor layout

### PR DESCRIPTION
**Pull request by doriroz**
changing the layout editor by creating a new sidebar to the right. 
placing  the position of the run button and the listdrop in the sidebar.
in addition, when error message is create it will display on the editor as a flow error text .
when the error text display, it can be close by the close button in the right side.
after i tried to close the error message and click the run button again the editor stay still and 
no error message is displayed.
i expect the error message will display as long as there is an error, 
but i don't know if that the way the editor should work.

### CODE REVIEW

**Comment by DhanushNehru** [comment]
Seems some merge conflicts, can you please resolve it @doriroz

**Comment by DhanushNehru** [comment]
@doriroz seems still there are merge conflicts in few files

**Comment by doriroz** [comment]
i get the above vercal message.
the pullrequest is waiting for authrization.

**Comment by doriroz** [comment]
I get this vercal message of failed to authrize deploy the pullreqeust.

**Comment by DhanushNehru** [comment]
Hi @doriroz vercel deployment approved

But I can still see a merge conflict in this file `src/pages/EditorComponent.js`

**Comment by doriroz** [comment]
Hi, i submitted my PR changes and i see it still waiting for approval.
can you please review on that PR and approve if its OK ?

**Comment by DhanushNehru** [comment]
Hi @doriroz seems the visualization looks odd in mobile view and also default code is not been pulled in your existing code which is already present, can you please check that

**Comment by doriroz** [comment]
Hi.... 
i didn't fit  the visualization looks to mobile view. on existing code it support with desktop view.
on my desktop view it look like the attached file
cd-editor

**Review by DhanushNehru — CHANGES_REQUESTED** [review]
Please check for the default code populated as well

**Comment by doriroz** [comment]
Hi....
what do you mean by the defaukt code populated ?

**Comment by DhanushNehru** [comment]
In the existing app whenever you pick js, python or any other language, you will see the default code populated in the console.
https://custom-code-editor.vercel.app/
Can you incorporate those changes which are already present in your PR ? @doriroz

**Pull request closed without merging**
