### PR TITLE
Added base64 encoding for api call

### LINKED ISSUE #125: External Api Not Working
I came across this repo, thought I could contribute, but the External API is not working. I am getting the submission token but not able to get the submission output as Accepted, either its Runtime Error or Compilation Error
Also I noticed the casing of header names were wrong, so I corrected them according Judge0 CE's requirement

### PR DESCRIPTION
**Pull request by PALASH2201**
Resolves #125 
### PR Fixes:
- 1 Modified the API URL to enforce base64 encoding.
- 2 Added base64 encoding to the code to be sent to external API.

### Checklist before requesting a review
- [ ] I have pull latest changes from `main` branch
- [ ] I have tested the changes locally
- [ ] I have run `npm run lint:fix` locally
- [ ] I have performed a self-review of my code
- [ ] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by DhanushNehru** [comment]
Hi @PALASH2201 please resolve merge conflicts and also make sure all the checklist has been reviewed as expected

**Comment by PALASH2201** [comment]
@DhanushNehru I'll look into it.

**Comment by PALASH2201** [comment]
@DhanushNehru Merge Conflicts are resolved

**Comment by PALASH2201** [comment]
@DhanushNehru Can you hacktoberfest-accepted and hacktoberfest labels?

**Pull request merged**
