### PR TITLE
Added Socket.io

### LINKED ISSUE #126: Integrating Socket.io for real time coding with peers
Hello @DhanushNehru,

I have an idea for the project that involves creating a backend server connected to a database.

The concept is to allow users to either join or create a room upon logging in. Users within a particular room will be able to write and sync code in real-time. For example, if I am writing something, the same code will be visible to other users in the room simultaneously.

In the past, I have built a similar application, and I would like to integrate this feature into your project as well, making it a real-time collaborative application. For the backend, I propose using Node.js, Express.js, MongoDB for the database, and Socket.io for WebSockets.

If you like this idea, please consider assigning this implementation to me. I am looking forward to contributing!

### PR DESCRIPTION
**Pull request by TheAdich**
Resolves #126
### PR Fixes:
- 1 Integrated Socket.io 
- 2

### Checklist before requesting a review
- [ ] I have pull latest changes from `main` branch
- [ ] I have tested the changes locally
- [ ] I have run `npm run lint:fix` locally
- [ ] I have performed a self-review of my code
- [ ] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by TheAdich** [comment]
Hello @DhanushNehru  Backend is being hosted on render it is running on a free version that is after a period of inactivity the server goes down and takes time to restart once a request is made . So either if you have other plans to host you can host on other platform too i have added server folder within the root directory of your project you could look into it.

**Comment by DhanushNehru** [comment]
Hi @TheAdich please mention the issue number properly in the PR

**Comment by Anikesh02** [comment]
> Hello @DhanushNehru Backend is being hosted on render it is running on a free version that is after a period of inactivity the server goes down and takes time to restart once a request is made . So either if you have other plans to host you can host on other platform too i have added server folder within the root directory of your project you could look into it.

To keep your backend alive every time, you can create a job in cron-job.org which will send a request to the backend every 1 min, solving the server going down issue.

**Comment by TheAdich** [comment]
Like video in the readme or here to show how i have implemented it ?

**Comment by TheAdich** [comment]
[screen-capture.webm](https://github.com/user-attachments/assets/f658381b-9728-4b10-b0af-6f1225c176a5)

**Comment by TheAdich** [comment]
On render you just need to choose web service and choose the repo where your backend is located in my case i had created a seperate repo and on render selected that repo 
Screenshot 2024-10-11 193901
Yo
Screenshot 2024-10-11 193922
Screenshot 2024-10-11 193947
in the build command just write npm install 
and in the start command write node index.js and choose the free plan and click on deploy
However if you are locally setting up the project you don;t need to configure the render

**Pull request closed without merging**
