### PR TITLE
Feature/notistac integration for better notifications

### LINKED ISSUE #43: [feature] Toaster for better notifications dispaly
we should toastify or notistack library for better success and error message shown.
It will also increase the UX

### PR DESCRIPTION
**Pull request by Chaitanya1672**
fixes #43 

I have added notistac library for toaster messages, which go along with MUI very easily.
With this library we can show success and error message fluently and with better UX

Demo:-
image

### CODE REVIEW

**Review by DhanushNehru — CHANGES_REQUESTED** [review]
Hi @Chaitanya1672 this popup happens only when the code editor is empty

But if there is an error in the code, it seems nothing is happening.

**Comment by Chaitanya1672** [comment]
> Hi @Chaitanya1672 this popup happens only when the code editor is empty
> 
> But if there is an error in the code, it seems nothing is happening.

@DhanushNehru 
I have written code for if response is not ok or api call is failed after clicking submission, what do you suggest should be added?

**Comment by DhanushNehru** [comment]
Can we have the error popped up when response is not ok or api call is failed after clicking submission, similar to what you have incorporated @Chaitanya1672

**Comment by Chaitanya1672** [comment]
> Can we have the error popped up when response is not ok or api call is failed after clicking submission, similar to what you have incorporated @Chaitanya1672

Yes that is happening, I have added notistack for that.
image

**Review by DhanushNehru — APPROVED** [review]

**Review by DhanushNehru — APPROVED** [review]

**Pull request merged**
