### PR TITLE
other languages are added to the compiler

### LINKED ISSUE #130: add few more programming languages to the project
I would like to add more languages such as:
- C
- Go
- PHP
- R
- Ruby
- SQL
- TypeScript

Along with the code snippets, icons and IDs

Could you assign it to me under Hacktoberfest.

### PR DESCRIPTION
**Pull request by chaanakyaaM**
Resolves #130 
### PR Fixes:
- 1.  Added 6 languages to the code editor

### Checklist before requesting a review
- [x] I have pull latest changes from `main` branch
- [x] I have tested the changes locally
- [ ] I have run `npm run lint:fix` locally
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by chaanakyaaM** [comment]
kindly let me know if there are any changes to be made.

**Review by DhanushNehru — CHANGES_REQUESTED** [review]
Please resolve merge conflicts @chaanakyaaM

**Comment by chaanakyaaM** [comment]
merge conflicts resolved.

**Review by DhanushNehru — CHANGES_REQUESTED** [review]
Hi @chaanakyaaM seems deployment has failed, please recheck the code

**Comment by chaanakyaaM** [comment]
ok

**Pull request closed without merging**
